spring:
  application:
    name: discodeit

  profiles:
    active: dev   # 로컬 기본 프로파일. 배포 시 -Dspring.profiles.active=prod 로 덮어씀

  jpa: #SQL로그 확인 + 테이블 자동 생성 방지(요구사항: DDL을 직접 작성하고 schema.sql에 포함하세요)
    hibernate:
      ddl-auto: validate        # schema.sql로 테이블 직접 관리할 거라 validate
    show-sql: true              # SQL 로그 출력
    properties:
      hibernate:
        format_sql: true        # SQL 보기 좋게 포맷
        use_sql_comments: true  # 어떤 쿼리인지 주석 표시
    open-in-view: false         # OSIV 비활성화(요구사항임)

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

discodeit:
  jwt:
    secret: ${JWT_SECRET}
    access-token-validity-seconds: ${JWT_ACCESS_TOKEN_VALIDITY_SECONDS:1800}      # 30분
    refresh-token-validity-seconds: ${JWT_REFRESH_TOKEN_VALIDITY_SECONDS:604800}  # 7일
  admin:
    email: ${ADMIN_EMAIL}
    password: ${ADMIN_PASSWORD}
  repository:
    type: file
    file-directory: .discodeit
  storage:
    type: ${STORAGE_TYPE:local}
    local:
      root-path: ${STORAGE_LOCAL_ROOT_PATH:.discodeit/storage}
    s3:
      region: ${AWS_S3_REGION}
      bucket: ${AWS_S3_BUCKET}
      presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:600}
info:
  app:
    name: Discodeit
    version: 1.7.0
    java:
      version: 17
    spring-boot:
      version: 3.4.0
  datasource:
    url: ${spring.datasource.url}
    driver-class-name: ${spring.datasource.driver-class-name}
  jpa:
    ddl-auto: ${spring.jpa.hibernate.ddl-auto}
  storage:
    type: ${discodeit.storage.type}
    path: ${discodeit.storage.local.root-path}
  multipart:
    max-file-size: ${spring.servlet.multipart.max-file-size}
    max-request-size: ${spring.servlet.multipart.max-request-size}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

logging:
  level:
    root: info # 기본 로깅 레벨
    org.springframework.security: trace